/* tailwind-config.js */
tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "on-tertiary-fixed-variant": "#00458e",
                "surface-bright": "#fcf8fb",
                "secondary-container": "#dfdfe1",
                "tertiary-container": "#ffffff",
                "tertiary": "#005cba",
                "on-surface": "#1b1b1d",
                "on-error-container": "#93000a",
                "surface-container-highest": "#e4e2e4",
                "tertiary-fixed": "#d7e3ff",
                "on-secondary-fixed-variant": "#454749",
                "secondary-fixed-dim": "#c6c6c8",
                "secondary-fixed": "#e2e2e4",
                "outline": "#747878",
                "tertiary-fixed-dim": "#aac7ff",
                "surface-container-high": "#eae7ea",
                "on-primary-container": "#747676",
                "on-surface-variant": "#444748",
                "primary-container": "#ffffff",
                "surface-container-low": "#f6f3f5",
                "primary-fixed": "#e2e2e2",
                "on-background": "#1b1b1d",
                "error-container": "#ffdad6",
                "surface": "#fcf8fb",
                "surface-dim": "#dcd9dc",
                "background": "#fcf8fb",
                "on-primary-fixed": "#1a1c1c",
                "surface-tint": "#5d5f5f",
                "inverse-surface": "#303032",
                "surface-container-lowest": "#ffffff",
                "surface-variant": "#e4e2e4",
                "inverse-primary": "#c6c6c7",
                "primary-fixed-dim": "#c6c6c7",
                "on-tertiary-fixed": "#001b3e",
                "error": "#ba1a1a",
                "on-error": "#ffffff",
                "on-tertiary": "#ffffff",
                "inverse-on-surface": "#f3f0f2",
                "on-tertiary-container": "#2474db",
                "surface-container": "#f0edef",
                "secondary": "#5d5e60",
                "primary": "#5d5f5f",
                "accent-blue": "#0066cc",
                "on-secondary-fixed": "#1a1c1d",
                "on-primary-fixed-variant": "#454747",
                "text-secondary": "#6e6e73",
                "on-secondary-container": "#616365",
                "on-secondary": "#ffffff",
                "on-primary": "#ffffff",
                "bg-parchment": "#f5f5f7",
                "outline-variant": "#c4c7c8"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            "spacing": {
                "section-v-padding-mobile": "80px",
                "margin-base": "32px",
                "headline-max-width": "800px",
                "prose-max-width": "680px",
                "gutter": "24px",
                "section-v-padding": "140px"
            },
            "fontFamily": {
                "hero-h1": ["Inter"],
                "overline": ["Inter"],
                "section-h2": ["Inter"],
                "section-h3": ["Inter"],
                "body": ["Inter"],
                "label": ["Inter"],
                "hero-h1-mobile": ["Inter"],
                "section-h2-mobile": ["Inter"]
            },
            "fontSize": {
                "hero-h1": ["80px", { "lineHeight": "1.1", "letterSpacing": "-0.028em", "fontWeight": "600" }],
                "overline": ["12px", { "lineHeight": "1.5", "letterSpacing": "0.08em", "fontWeight": "600" }],
                "section-h2": ["56px", { "lineHeight": "1.1", "letterSpacing": "-0.028em", "fontWeight": "600" }],
                "section-h3": ["28px", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "400" }],
                "body": ["17px", { "lineHeight": "1.47", "letterSpacing": "-0.022em", "fontWeight": "400" }],
                "label": ["14px", { "lineHeight": "1.2", "fontWeight": "500" }],
                "hero-h1-mobile": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "600" }],
                "section-h2-mobile": ["36px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "600" }]
            }
        },
    },
};
